"""Fast, side-effect-free validation for Python files generated by SAM-AI."""

from __future__ import annotations

import ast
import builtins
import json
import pathlib
import sys


def module_definitions(tree: ast.Module) -> set[str]:
    names = set(dir(builtins)) | {"__name__", "__file__", "__package__", "__doc__"}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                names.add(alias.asname or alias.name.split(".")[0])
        elif isinstance(node, (ast.Assign, ast.AnnAssign, ast.AugAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                for child in ast.walk(target):
                    if isinstance(child, ast.Name):
                        names.add(child.id)
    # Include assignments nested under module-level if/try/with blocks and local
    # variables so the conservative checker does not report ordinary Python scope
    # patterns as failures. Missing constant-style globals remain detectable.
    for child in ast.walk(tree):
        if isinstance(child, ast.Name) and isinstance(child.ctx, (ast.Store, ast.Param)):
            names.add(child.id)
        elif isinstance(child, ast.ExceptHandler) and child.name:
            names.add(child.name)
    return names


class UndefinedGlobalVisitor(ast.NodeVisitor):
    def __init__(self, known: set[str]) -> None:
        self.known = known
        self.scope_depth = 0
        self.missing: dict[str, int] = {}

    def _visit_scope(self, node: ast.AST) -> None:
        # Names assigned anywhere in a Python function are local to that function.
        # Everything else must resolve through the module or builtins. This catches
        # common generated-code mistakes such as using PURPLE without defining it.
        local_names = {
            child.id
            for child in ast.walk(node)
            if isinstance(child, ast.Name) and isinstance(child.ctx, (ast.Store, ast.Param))
        }
        args = getattr(node, "args", None)
        if args is not None:
            local_names.update(arg.arg for arg in (*args.posonlyargs, *args.args, *args.kwonlyargs))
            if args.vararg:
                local_names.add(args.vararg.arg)
            if args.kwarg:
                local_names.add(args.kwarg.arg)
        self.scope_depth += 1
        for child in ast.walk(node):
            if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load):
                # Restrict the heuristic to constant-style globals. Python permits
                # many dynamic closure/import patterns, while generated Pygame
                # failures commonly come from missing color/config constants.
                if child.id.isupper() and child.id not in local_names and child.id not in self.known:
                    self.missing.setdefault(child.id, child.lineno)
        self.scope_depth -= 1

    visit_FunctionDef = _visit_scope
    visit_AsyncFunctionDef = _visit_scope

    def visit_Name(self, node: ast.Name) -> None:
        if isinstance(node.ctx, ast.Load) and self.scope_depth == 0 and node.id not in self.known:
            self.missing.setdefault(node.id, node.lineno)


def main() -> int:
    path = pathlib.Path(sys.argv[1])
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source, filename=str(path))
        compile(tree, str(path), "exec")
    except (SyntaxError, ValueError) as exc:
        print(json.dumps({"ok": False, "detail": f"Python syntax error: {exc}"}))
        return 1

    known = module_definitions(tree)
    visitor = UndefinedGlobalVisitor(known)
    for statement in tree.body:
        visitor.visit(statement)
    if visitor.missing:
        details = ", ".join(f"{name} (line {line})" for name, line in sorted(visitor.missing.items()))
        print(json.dumps({"ok": False, "detail": "Possibly undefined names: " + details}))
        return 2
    print(json.dumps({"ok": True, "detail": "Python syntax and top-level name checks passed."}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
