param([Parameter(Mandatory=$true)][ValidateSet('block','allow','unblock','lockdown_on','lockdown_off','rule_enable','rule_disable','rule_remove','policy_enable','policy_disable','policy_remove')][string]$Action,[string]$AppName='',[string]$AppPath='',[string]$RuleName='',[string]$ResultPath='')
$ErrorActionPreference='Stop'
function Write-Result([bool]$Success,[string]$Message) { if($ResultPath){@{success=$Success;action=$Action;message=$Message;time=(Get-Date).ToString('o')}|ConvertTo-Json|Set-Content -LiteralPath $ResultPath -Encoding UTF8} }
try {
 if($Action -in @('lockdown_on','lockdown_off')) { $names=@('SAM Network Guard - EMERGENCY LOCKDOWN - IN','SAM Network Guard - EMERGENCY LOCKDOWN - OUT'); Get-NetFirewallRule -DisplayName $names -ErrorAction SilentlyContinue | Remove-NetFirewallRule; if($Action -eq 'lockdown_on'){New-NetFirewallRule -DisplayName $names[0] -Direction Inbound -Action Block -Profile Any -Enabled True|Out-Null; New-NetFirewallRule -DisplayName $names[1] -Direction Outbound -Action Block -Profile Any -Enabled True|Out-Null}; Write-Result $true $(if($Action -eq 'lockdown_on'){'Internet lockdown rules are active.'}else{'Internet lockdown rules were removed.'}); exit 0 }
 if($Action -in @('rule_enable','rule_disable','rule_remove')) { if($RuleName -notlike 'SAM Network Guard -*'){throw 'Only SAM-owned rules can be changed here.'}; $target=Get-NetFirewallRule -DisplayName $RuleName -ErrorAction Stop; if($Action -eq 'rule_remove'){$target|Remove-NetFirewallRule}else{$target|Set-NetFirewallRule -Enabled $(if($Action -eq 'rule_enable'){'True'}else{'False'})}; Write-Result $true "Firewall rule action completed: $Action"; exit 0 }
 if($Action -in @('policy_enable','policy_disable','policy_remove')) { $targets=@(foreach($rule in Get-NetFirewallRule -DisplayName 'SAM Network Guard -*' -ErrorAction SilentlyContinue){$filter=Get-NetFirewallApplicationFilter -AssociatedNetFirewallRule $rule|Select-Object -First 1;if([string]$filter.Program -ieq $AppPath){$rule}}); if($targets.Count -eq 0){throw 'No matching SAM firewall policy was found.'}; if($Action -eq 'policy_remove'){$targets|Remove-NetFirewallRule}else{$targets|Set-NetFirewallRule -Enabled $(if($Action -eq 'policy_enable'){'True'}else{'False'})}; Write-Result $true "Application policy action completed: $Action"; exit 0 }
 if(-not(Test-Path -LiteralPath $AppPath -PathType Leaf)){throw 'The selected executable no longer exists.'}
 $safeName=($AppName -replace '[^a-zA-Z0-9._ -]','').Trim(); if(-not $safeName){$safeName=[IO.Path]::GetFileName($AppPath)}
 $names=@("SAM Network Guard - $safeName - IN","SAM Network Guard - $safeName - OUT"); Get-NetFirewallRule -DisplayName $names -ErrorAction SilentlyContinue|Remove-NetFirewallRule
 if($Action -in @('block','allow')){$ruleAction=if($Action -eq 'block'){'Block'}else{'Allow'}; New-NetFirewallRule -DisplayName $names[0] -Direction Inbound -Action $ruleAction -Program $AppPath -Profile Any -Enabled True|Out-Null; New-NetFirewallRule -DisplayName $names[1] -Direction Outbound -Action $ruleAction -Program $AppPath -Profile Any -Enabled True|Out-Null}
 Write-Result $true "Application firewall action completed: $Action ($safeName)"; exit 0
} catch { Write-Result $false $_.Exception.Message; exit 1 }
